### ISSUE TITLE
サイドメニュー下の2020 Tokyo Metropolitan Governmentを山形版に直す

### ISSUE THREAD

**Issue by yuuton414** [yamaserif/covid19#23]
## 起こっている問題 / The Problem
-「2020 Tokyo Metropolitan Government」のままになっている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/59001145/78513051-e7e44600-77e3-11ea-9ab7-221be5aa5feb.png)

## 期待する見せ方・挙動 / Expected Behavior
- 山形版にするor削除？する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yamaserif** [comment]
@yuuton414
Issueありがとうございます！
有志によるサイトなので文言を少し悩んだのですが、新潟県のサイト表記がいい感じでしたのでこのような修正としました！
