### ISSUE TITLE
スマホから見た場合に「お知らせ」の下にページ番号が改行されずに表示される

### ISSUE THREAD

**Issue by y2naranja** [yamaserif/covid19#234]
## 起こっている問題 / The Problem
- スマホ(Android)で表示させると、「お知らせ」の下に過去のお知らせのページ番号と思しき番号が表示される

## スクリーンショット / Screenshot
![Screenshot_20201127-182157-picsay](https://user-images.githubusercontent.com/912713/100433618-a986f880-30de-11eb-8d86-d0656ca1973f.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- ページ番号の部分を折り返して表示させる

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- Android
- Chrome / Firefox / Edge / Opera

**Comment by yamaserif** [comment]
Issueありがとうございます。
こちら、現状を鑑みるに更にページが増えることを考え、以下のように表示数を制限する対応といたしました。
以上、よろしくお願いいたします。
![image](https://user-images.githubusercontent.com/62947068/101663675-57ef4e00-3a8e-11eb-9a96-e740499bf2a8.png)
