### ISSUE TITLE
免責事項の記載が東京のままになっている

### ISSUE THREAD

**Issue by capytan** [yamaserif/covid19#27]
## 改善詳細 / Details of Improvement
- 免責事項の記述に東京都のものが残っていました。
> 当サイトに掲載されている情報の正確性については万全を期していますが、東京都は利用者が当サイトの情報を用いて行う一切の行為について責任を負うものではありません。

## スクリーンショット / Screenshot
![スクリーンショット 2020-04-08 17 29 14](https://user-images.githubusercontent.com/38171239/78762307-a8be1c80-79be-11ea-8995-5e085ead116f.png)

## 期待する見せ方・挙動 / Expected behavior
- ` 東京都 ` を ` 山形県またはサイト運営者 ` 等に修正する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yamaserif** [comment]
@capytan
Issueありがとうございます。
文言修正のプルリク#29 を出しました。
